spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://107.180.48.95:3306/BD_NutriCoach
    username: Enzzouser
    password: nutricoachuser
  jpa:
    database: MYSQL
    hibernate.ddl-auto: update
    show-sql: true